import Head from "next/head";
import Link from "next/link";
import { useContext, useEffect, useState } from "react";
import { BlogContext } from "./context/BlogContext";
import { SearchContext } from "./context/searchContext";
export default function Home() {
  const { data, dispatch } = useContext(BlogContext);
  const { searchData, searchDispatch } = useContext(SearchContext);
  const [blogs, setBlogs] = useState(data.allBlogs);

  // const filteredBlogs = data.allBlogs.filter((blog) => blog.title.includes(searchData.searchBlog));
  return (
    <>
      <Head>
        <title>CodingBlogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="nextjs, next blog, hunting coders" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`text-white ${blogs.length == 0 ? 'h-screen' : 'h-full'}`}>
        <div className="flex flex-col justify-center items-center">
          <h1 className="text-2xl font-bold">
            CodingBlogs
          </h1>
          <p
            className="opacity-60"
          >Blogs for coders by codingBlogs</p>
          {/* <div className="max-w-2xl gap-10"> */}
          <div className="flex flex-col gap-10 m-5 text-black text-xl max-w-2xl">
            {
              searchData && (searchData?.searchBlog == "") ? (
                <>
                  <h2>latest Blog</h2>
                  <div className="cursor-pointer">
                    <h1 className="font-bold">how to learn javascript react?</h1>
                    <p className="opacity-70">JavaScript is the language used for webdevelopment.</p>
                  </div>
                  <div className="cursor-pointer">
                    <h1 className="font-bold">how to learn javascript react?</h1>
                    <p className="opacity-70">JavaScript is the language used for webdevelopment.</p>
                  </div>
                  <div className="cursor-pointer">
                    <h1 className="font-bold">how to learn javascript react?</h1>
                    <p className="opacity-70">JavaScript is the language used for webdevelopment.</p>
                  </div>
                  <div className="cursor-pointer">
                    <h1 className="font-bold">how to learn javascript react?</h1>
                    <p className="opacity-70">JavaScript is the language used for webdevelopment.</p>
                  </div>
                </>
              ) : (
                data?.allBlogs?.filter((blog) => blog.title.includes(searchData.searchBlog)).map((blogItem, indx) => {
                  return (
                    <div
                      className="text-black"
                      key={`${blogItem.slug}${indx}`}>
                      <Link href={`/blogpost/${blogItem.slug}`}>
                        <h1
                          className='font-bold'
                        >{blogItem.title}</h1>
                      </Link>
                      <p
                        className='opacity-70'
                      >
                        {`${blogItem.content.slice(0, 180)}...`}
                      </p>
                    </div>
                  )
                })
              )
            }
          </div>
        </div>
      </div>
    </>
  );
}
